import argparse
import matplotlib
# Do not use any X11 backend
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
import os
import pcapy
import statsmodels.api as sm

parser = argparse.ArgumentParser(
    description="Summarize stat files generated by analyze")
parser.add_argument("pcap", help="path to the pcap to compute CDF")

args = parser.parse_args()

reader = pcapy.open_offline(args.pcap)
sizes = []

while True:
    try:
        (header, payload) = reader.next()
        sizes.append(header.getlen())
    except pcapy.PcapError:
        break

plt.figure()
plt.clf()
fig, ax = plt.subplots()

graph_fname = "cdf_size_packets_" + os.path.splitext(args.pcap)[0] + ".pdf"

try:
    sample = np.array(sorted(sizes))

    ecdf = sm.distributions.ECDF(sample)

    x = np.linspace(min(sample), max(sample))
    y = ecdf(x)
    ax.step(x, y, color='b')
except ZeroDivisionError as e:
    print(str(e))

# Shrink current axis's height by 10% on the top
box = ax.get_position()
ax.set_position([box.x0, box.y0,
                 box.width, box.height * 0.9])

# Put a legend above current axis
# ax.legend(loc='lower center', bbox_to_anchor=(0.5, 1.05), fancybox=True, shadow=True, ncol=len(aggl_res[cond]))

plt.xlabel('Size of packets in bytes', fontsize=18)
plt.savefig(graph_fname)
plt.close('all')
